VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsTask"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Attribute VB_Ext_KEY = "SavedWithClassBuilder6" ,"Yes"
Attribute VB_Ext_KEY = "Top_Level" ,"Yes"
Option Explicit


Public Filename             As String
Public Path                 As String
Public FileDate             As Date
Public lFileSize            As Long
Public CompanyName          As String
Public FileDescription      As String
Public FileVersion          As String
Public InternalName         As String
Public LegalCopyright       As String
Public OriginalFileName     As String
Public ProductName          As String
Public ProductVersion       As String
Public Comments             As String
Public LegalTrademarks      As String
Public PrivateBuild         As String
Public SpecialBuild         As String
Public FileType             As String
Public FileFlags            As String
Public FileOS               As String



